baseurl = "https://erkanerol.github.io/"
languageCode = "en-en"
title = "Blog"

theme = "hugo-paper"
paginate = 10

enableRobotsTXT = true

[author]
    name = "Erkan Erol"

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[params]
    # Metadata used to drive integrations.
    googleAnalytics = "UA-57796113-2"

    # Sidebar social links, these must be full URLs.
    github = "erkanerol"
    linkedin = "/in/erkanerol"
    twitter = "erkan_erol_"
    instagram= "theerkanerol"

    avatar="https://www.gravatar.com/avatar/321108fd00753fd95baeddbc3abc8a76"
    name="Erkan Erol"
    bio="Software Crafter"

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link

    [[menu.main]]
    name = "Turkish"
    pre = " "
    weight = -110
    identifier = "Turkish"
    url = "/tags/Turkish/"

    [[menu.main]]
    name = "English"
    pre = " "
    weight = -100
    identifier = "English"
    url = "/tags/English/"

    [[menu.main]]
    name = "Tags"
    pre = " "
    weight = -100
    identifier = "Tags"
    url = "/tags/"
