baseurl = "https://erkanerol.github.io/"
languageCode = "en-en"
title = "Blog"

theme = "hugo-paper"
paginate = 10

enableRobotsTXT = true

[author]
    name = "Erkan Erol"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[markup.goldmark.renderer]
    unsafe = true

[params]

    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Erkan Erol's Blog"
    defaultKeywords = "software,books,software craftsmanship,erkan erol,blog"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "monokai"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-57796113-2"

    # Sidebar social links, these must be full URLs.
    github = "erkanerol"
    linkedin = "https://www.linkedin.com/in/erkan-erol-26488b91?"
    twitter = "erkan_erol_"
    instagram= "theerkanerol"

    avatar="https://www.gravatar.com/avatar/321108fd00753fd95baeddbc3abc8a76"
    name="Erkan Erol"
    bio="Software Crafter"

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link

    [[menu.main]]
    name = "Turkish"
    pre = " "
    weight = -110
    identifier = "TR"
    url = "/categories/tr/"

    [[menu.main]]
    name = "English"
    pre = " "
    weight = -100
    identifier = "EN"
    url = "/categories/en/"