baseurl = "https://erkanerol.github.io/"
locale = "en-en"
title = "Blog"

theme = "hugo-paper"
enableRobotsTXT = true

[pagination]
    pagerSize = 10

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[services.googleAnalytics]
    id = "G-W6KGPMEHXB"

[params]
    author = { name = "Erkan Erol" }

    # Sidebar social links, these must be full URLs.
    github = "erkanerol"
    linkedin = "/in/erkanerol"
    twitter = "erkan_erol_"
    instagram= "theerkanerol"

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link

    [[menu.main]]
    name = "Turkish"
    pre = " "
    weight = -110
    identifier = "Turkish"
    url = "/tags/Turkish/"

    [[menu.main]]
    name = "English"
    pre = " "
    weight = -100
    identifier = "English"
    url = "/tags/English/"

    [[menu.main]]
    name = "Tags"
    pre = " "
    weight = -100
    identifier = "Tags"
    url = "/tags/"
